// <auto-generated />
using System;
using Example1.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Example1.Migrations
{
    [DbContext(typeof(Example1MigrationDbContext))]
    partial class Example1MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Example1.Models.Product", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "Price");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Example1.Models.SaleItem", b =>
                {
                    b.Property<string>("SaleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProductPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SaleName", "Price");

                    b.HasIndex("ProductName", "ProductPrice");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("Example1.Models.SaleItem", b =>
                {
                    b.HasOne("Example1.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductName", "ProductPrice");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
